name: Test Reusable WorkFlow user

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/*'
      - '!master'
      - '!main'
  pull_request:
    branches: 
      - 'master'
      - 'main'
  release:
    types:
      - 'published'

env:
  # You can use repository name or change the name
  # For example: 
  # change REPO_NAME: ${{ github.event.repository.name }} for REPO_NAME: "abc" 
  REPO_NAME: ${{ github.event.repository.name }}
  # TAG: ${{ github.event.release.tag_name }}
  # BASE_BRANCH: ${GITHUB_REF#refs/*/}

jobs:
  build:
    uses: gudiaolabs/docker-build/.github/workflows/dockerbuild.yml@main
    with:
      image_name: node-helloworld-github-actions
      tag: $GITHUB_RUN_NUMBER
    secrets:
      registry_username: ${{ secrets.DOCKER_USER }}
      registry_password: ${{ secrets.DOCKER_PASSWORD }}

  # build-ecr:
  #   if: github.event_name == 'release' && github.event.action == 'published'
  #   uses: gudiaolabs/docker-build-push-ecr/.github/workflows/dockerbuildpushecr.yml@main
  #     image_name: ${{ env.REPO_NAME }}
  #     tag: 'v0.0.1'
  #   secrets: 
  #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # slack:
  #   if: github.event_name == 'release' && github.event.action == 'published'  
  #   uses: gudiaolabs/slack-notify/.github/workflows/slack-notify.yml@main
  #   secrets: 
  #     slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}







