name: Test Reusable WorkFlow user

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/*'
      - '!master'
      - '!main'
  pull_request:
    types:
      - 'closed'
  release:
    types:
      - 'published'

env:
  # You can use repository name or change the name
  # For example: 
  # change REPO_NAME: ${{ github.event.repository.name }} for REPO_NAME: "abc" 
  REPOSITORY_NAME: ${{ github.event.repository.name }}
  # TAG: ${{ github.event.release.tag_name }}
  # BASE_BRANCH: ${GITHUB_REF#refs/*/}

jobs:
  test: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "Hello, world! Hi $REPOSITORY_NAME"

      - name: Set env
        run: echo "REPO_NAME=$(echo $REPOSITORY_NAME)" >> $GITHUB_ENV

      - name: Test
        run: echo $REPO_NAME

  build:
    needs: [test]
    uses: gudiaolabs/docker-build/.github/workflows/dockerbuild.yml@main
    with:
      image_name: $ {{ env.REPO_NAME }}

  # build-ecr:
  #   if: github.event_name == 'release' && github.event.action == 'published'
  #   uses: gudiaolabs/docker-build-push-ecr/.github/workflows/dockerbuildpushecr.yml@main
  #   with:
  #     ecr_repository: $REPO_NAME
  #     image_tag: 'v0.0.1'
  #   secrets: 
  #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # slack:
  #   if: github.event_name == 'release' && github.event.action == 'published'  
  #   uses: gudiaolabs/slack-notify/.github/workflows/slack-notify.yml@main
  #   secrets: 
  #     slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}







