name: Test Reusable WorkFlow user

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/*'
      - '!master'
      - '!main'
  pull_request:
    types:
      - 'closed'
  release:
    types:
      - 'published'

jobs:

  build:
    uses: gudiaolabs/docker-build/.github/workflows/dockerbuild.yml@main
    with:
      image_name: ${{ github.event.repository.name }}

  # build-ecr:
  #   if: github.event_name == 'release' && github.event.action == 'published'
  #   uses: gudiaolabs/docker-build-push-ecr/.github/workflows/dockerbuildpushecr.yml@main
  #   with:
  #     ecr_repository: $REPO_NAME
  #     image_tag: 'v0.0.1'
  #   secrets: 
  #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # slack:
  #   if: github.event_name == 'release' && github.event.action == 'published'  
  #   uses: gudiaolabs/slack-notify/.github/workflows/slack-notify.yml@main
  #   secrets: 
  #     slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}







