name: Test Reusable WorkFlow user

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/*'
      - '!master'
      - '!main'
  pull_request:
    types:
      - 'closed'
  release:
    types:
      - 'published'

jobs:
  EnvSetup:
    name: Setup Dynamic Environment Variables
    runs-on: ubuntu-latest
    outputs:
      repository-name: ${{ steps.set-output-defaults.outputs.repository-name }}
      tag: ${{ steps.set-output-defaults.outputs.tag }}
    steps:
      - name: set outputs with default values
        id: set-output-defaults
        run: |    
          echo "::set-output name=repository-name::${{ github.event.repository.name }}"
          echo "::set-output name=tag::${{ github.event.release.tag_name }}"

  build:
    needs: [EnvSetup]
    uses: gudiaolabs/docker-build/.github/workflows/dockerbuild.yml@main
    with:
      image_name: ${{ needs.EnvSetup.outputs.repository-name }}

  build-ecr:
    needs: [EnvSetup]
    if: github.event_name == 'release' && github.event.action == 'published'
    uses: gudiaolabs/docker-build-push-ecr/.github/workflows/dockerbuildpushecr.yml@main
    with:
      ecr_repository: ${{ needs.EnvSetup.outputs.repository-name }}
      image_tag: ${{ needs.EnvSetup.outputs.tag }}
    secrets: 
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  slack:
    needs: [build-ecr]
    if: github.event_name == 'release' && github.event.action == 'published'  
    uses: gudiaolabs/slack-notify/.github/workflows/slack-notify.yml@main
    secrets: 
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}







